config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    root    'profiles#show_my_profile'

            #UserController
    get 'user_signup'    => 'users#new'
    
    post 'user_login'    => 'users#login'

    delete 'user_logout' => 'users#destroy'

    get 'user_logout' => 'users#destroy'




    get "show_my_profile" => "profiles#show_my_profile"


    get 'users/:id/:tab' => 'profiles#show_tabs'
    

    #Issues
    get 'add_issue_view' => 'issues#add_issue_view'
    post 'add_issue' => 'issues#add_issue'
    post 'add_issue_comment' => 'issues#add_issue_comment'

    get 'issues/:id/' => 'issues#open_issue'

    post 'user_close_ticket' => 'issues#user_close_ticket'
    post 'user_reopen_ticket' => 'issues#user_reopen_ticket'
    post 'agent_close_ticket' => 'issues#agent_close_ticket'
    post 'agent_assign_ticket' => 'issues#agent_assign_ticket'



    get 'admin/:name' => 'profiles#admin_view'
    post 'user_suspend' => 'profiles#user_suspend'

    get 'generate_report' => 'profiles#generate_report'

    




    

    resources :users  


end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
include MarkdownHelper
   include UsersHelper
   include IssuesHelper

    def add_issue_view
        @type="add_issue_view"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end
    end
    
    def add_issue
        @success=false
        begin
            throw "not logged in" unless current_user
            heading=params[:data][:heading]
            content=params[:data][:content]

            parsed_content=Markdown.render(content)
            if heading.length>=3
                @ticket=Ticket.new(created_by: current_user.id,heading:heading)
                @success=@ticket.save
                if @success
					actualcontent=ActualContent.new(content: content)
                	actualcontent.save

                	@ticket_data=TicketDatum.new(ticket_id:@ticket.id, content: parsed_content,
                		actual_content_id: actualcontent.id)
                	@ticket_data.save
                	

                end
            end
       	rescue Exception=> ex
            #debugger

        end

        @type="add_issue"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end
    end

    def add_issue_comment
        @success=false
        begin
            throw "not logged in" unless current_user
            comment=params[:comm][:content]
            ticket_id=params[:id]

            @ticket=Ticket.find_by(id:ticket_id);

            if comment.length>=1 && @ticket
                add_comment @ticket, comment
            end
        rescue Exception=> ex
            debugger

        end

        @type="add_issue_comment"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end
    end

    def open_issue
      	@success=false
        begin
            throw "not logged in" unless current_user
            id=params[:id]

            @ticket=Ticket.find_by(id:id);
            if( @ticket && access( @ticket))
            	open_issue_data id
            	@success=true
                if current_user.agent?
                    @agent_list=User.where(user_type:1).pluck(:username)
                end
            end
       	rescue Exception=> ex
            #debugger

        end

        @type="open_issue"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
            format.html do 
                render "users/show"
            end
        end
    end

    def user_close_ticket
        begin
            throw "not logged in" unless current_user
            id=params[:id]

            @ticket=Ticket.find_by(id:id);
            if( @ticket && access( @ticket))
                @ticket.close
                add_comment @ticket, "Ticket Closed"


                open_issue_data id
            end
        rescue Exception=> ex
        end

        @type="open_issue"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end 
    end

    def user_reopen_ticket
        begin
            throw "not logged in" unless current_user
            id=params[:id]

            @ticket=Ticket.find_by(id:id);
            if( @ticket && access( @ticket))
                @ticket.reopen
                add_comment @ticket, "Ticket Reopened"

                open_issue_data id
            end
        rescue Exception=> ex
        end

        @type="open_issue"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end 
    end

    def agent_close_ticket
        begin
            throw "not logged in" unless current_user
            id=params[:id]

            @ticket=Ticket.find_by(id:id);
            if( @ticket && access( @ticket) )
                @ticket.close
                add_comment @ticket, "Ticket Closed by agent"

                open_issue_data id
            end
        rescue Exception=> ex
        end

        @type="open_issue"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end 
    end

    def agent_assign_ticket
        begin
            throw "not logged in" unless current_user
            id=params[:id]
            username=params[:info][:agent_name]
            user=get_assigned_person username

            throw "not assignable " unless assignable user

            @ticket=Ticket.find_by(id:id);
            if( @ticket && access( @ticket) )
                @ticket.open user.id
                add_comment( @ticket, "Ticket Assigned to agent " +user.username)

                open_issue_data id
            end
        rescue Exception=> ex
        end

        @type="open_issue"
        respond_to do |format|
            format.js {render :file => "issues/issues.js.erb" }
        end 
    end


    private

        def get_assigned_person username
           begin
                if current_user.username==username
                    return current_user
                else
                    user=User.find_by(username:username)
                    return user
                end
            rescue
                return nil
            end 
        end

        def assignable user
            begin
                return true if user.agent?
            rescue
                return false
            end
        end

        def add_comment ticket, comment
            parsed_content=Markdown.render(comment)

            actualcontent=ActualContent.new(content: comment)
            @success=   actualcontent.save
            
            if @success
                @comment=Comment.new(ticket_id: ticket.id,user_id: current_user.id,comment:parsed_content,actual_content_id: actualcontent.id)
                @success=@comment.save
            end
            comments=[]
            comments.push @comment
            get_userlist comments
        end

        def open_issue_data id
            @ticketdata=TicketDatum.find_by(ticket_id: id)
            @comments=Comment.where(ticket_id: id).limit(30)

            @user_list=get_userlist @comments
        end

        def access ticket
            if current_user.user? 
                return ticket.created_by==current_user.id#if user only created guy can see
            else
                if ticket.new? 
                    return true#any agent can see new issue
                else
                    return @ticket.assigned_to==current_user.id #only agent working on it can see
                end

            end
        end
end

app/helpers/issues_helper.rb
module IssuesHelper

    def get_userlist comments
    	begin
	    	user_ids=comments.pluck(:user_id)

	    	users=User.where("id in (?)",user_ids)

	    	@user_map={}
	    	users.each do |user|
	    		@user_map[user.id]=user
	    	end

	    rescue
	    	return {} 
	    end


    end

end

app/views/issues/_agent_buttons.html.erb
<%if @ticket.new? %>
    <div class="row">
        <div class="col-md-3 pull-right">     
              <div class="btn-group">
                  <button type="button" class="btn btn-success" id='agent_assign_ticket' ticketid="<%=@ticket.id%>" >Assign Ticket</button>
                  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-cog"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    <li><%= link_to "Placeholder" , '#', method:  :get, remote:true , id:""%></li>
                </ul>
              </div>

        </div>

    </div>
<%elsif @ticket.open?  %>
    <div class="row">
             <div class="col-md-3 pull-right">     
              <div class="btn-group">
                  <button type="button" class="btn btn-success" id='agent_close_ticket' ticketid="<%=@ticket.id%>">Close Ticket</button>
                  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-cog"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    <li><button type="button" class="btn btn-success" id='agent_assign_ticket' ticketid="<%=@ticket.id%>" >Assign Ticket</button></li>
                </ul>
              </div>

          </div>

        </div>

    </div>
<%end%>


            <div class="container hide" id="agentassignarea">
                  <div class="row">
                    <div class="col-sm-6">
                      <%= form_for(:info, url: agent_assign_ticket_path(id: @ticket.id),remote:true) do |f| %>
                          <%=   f.text_field :agent_name ,placeholder:"Agent Name", title:"Please type agent Name", 
                          class: 'form-control',id:"agent_picker"%>

                          <%=   f.submit 'Assign', class: 'finish btn btn-primary'%>
                        <% end%>
                    </div>    

                  </div>
                </div>

  <script type="text/javascript">
    <% if @agent_list && @agent_list.length>0%>
        var agents="<%=@agent_list.join(",")%>";
        var availableTags =  agents.split(",");


$( "#agent_picker" ).autocomplete({
      source: availableTags,zindex:30
    });
    <%end%>
  </script>

app/views/issues/_create_issue.html.erb
<%if action=="create"%>
<div class="container">
    <div class="row">
        <div id="">
            <%= form_for(:data, url: add_issue_path,remote:true) do |f| %>
                <%= f.text_field :heading, class:"form-control",placeholder:"Enter  Heading",id:"issue_heading"%>

                <%= f.text_area :content, class:"form-control",placeholder:"Issue Description",data:{provide:"markdown"},:size => "100x10" ,id:"issue_editor"%>

                <%= f.submit 'Save', class: 'btn btn-primary'%>
            <% end%>
        </div>
    </div>

</div>
<script>
$(document).ready(
  function () {
     
        $('#issue_editor').markdown({autofocus:false,savable:false});
  }

);
</script>
<%elsif action=="created" %>
    <div class="[ panel panel-default ] panel-google-plus ">
                   <div class="panel-google-plus-tags" id="">
                       <%tag='Todo'%>
                    <ul>
                        <li><%=tag%></li>                       
                    </ul>
                </div>
        <h3>Issue created</h3>      

        <div class="panel-heading"><h2><%=@ticket.heading%></h2>
        </div>
        <div class="panel-body " id="">
                <div class="row">
                    <div class="">
                        <%=@ticket_data.content.html_safe%>
                    </div>

			     </div>
        </div>

    </div>
   
<%end%>

app/views/issues/_issue.html.erb
<%if @success==false%>
<p>You dont have access to see this</p>
<%else%>
    <%if current_user.user?%>
       <%= render  :partial => 'issues/user_buttons'%>

    <%else%>
       <%= render  :partial => 'issues/agent_buttons'%>
    <%end%>
     <div class="col-md-9">
            <div class="detailBox">
                <div class="titleBox">
                  <label><h4><%=@ticket.heading%></h4></label>
                </div>
                <div class="commentBox">
                    <div class="post_content_actual">
                    	<%=@ticketdata.content.html_safe%>
                    </div>

                </div>

                <div class="actionBox">

                    <ul class="commentList">
                        <% @comments && @comments.each do |comment| %>
                               <%= render  :partial => 'issues/issue_comment',locals:{comment:comment}%>

                        <%end%>


                    </ul>



                        <div class="row">
                            <%= form_for(:comm, url: add_issue_comment_path(id: @ticket.id),remote:true) do |f| %>
                                <div class="col-md-9">
                                    <%=     f.text_area :content, id:'comment_area',class:"form-control",placeholder:"Reply to this conversation" %>

                                     <%=     f.submit 'Submit', class: 'btn btn-primary'%>

                                </div>


                          <% end%>
                        </div>








                </div>

            </div>
    </div>
<%end%>
<script>

$(document).ready(
  function () {
     
        $('#comment_area').markdown({autofocus:false,savable:false});
  }

);
</script>

app/views/issues/_issue_comment.html.erb
<li id="issue_comments">

	 <div class="commenterImage">
		<%user=@user_map[ comment.user_id]%>
		<%= image_tag( user.get_profile_pic , style:"width: 30px; height: 40px;") %>

	</div>
	<div class="commentText">
		<h4><%=user.username%> : </h4><p class=""><%=comment.comment.html_safe%></p> <span class="date sub-text">on <%=comment.created_at%></span>

	</div>
</li>

app/views/issues/_user_buttons.html.erb
<%if @ticket.new? %>
    <div class="row">
        <div class="col-md-3 pull-right">     
              <div class="btn-group">
                  <button type="button" class="btn btn-success" id='user_close_ticket' ticketid="<%=@ticket.id%>" >Close Ticket</button>

              </div>

        </div>

    </div>
<%elsif @ticket.open?  %>
    <div class="row">
             <div class="col-md-3 pull-right">     
              <div class="btn-group">
                  <button type="button" class="btn btn-success" id='user_close_ticket' ticketid="<%=@ticket.id%>">Close Ticket</button>
 
              </div>

          </div>

        </div>

    </div>
<%else%>

    <div class="row">
        <div class="col-md-3 pull-right">     

              <div class="btn-group">
                  <button type="button" class="btn btn-success" id='user_reopen_ticket' ticketid="<%=@ticket.id%>">Reopen Ticket</button>

              </div>

        </div>

    </div>
<%end%>

app/views/issues/issues.js.erb
<%if @type=="add_issue_view"%> 
    $('#post_area').html("<%= escape_javascript (render  :partial => 'issues/create_issue',locals:{action:'create'} )  %>");

<%elsif @type=="add_issue"%> 
    $('#post_area').html("<%= escape_javascript (render  :partial => 'issues/create_issue',locals:{action:'created'} )  %>");
<%elsif @type=="add_issue_comment"%> 
    $('.commentList').append("<%= escape_javascript (render  :partial => 'issues/issue_comment',locals:{comment:@comment} )  %>");
	$('#comment_area').val("");
<%elsif @type=="open_issue"%> 
    $('.post_area2').html("<%= escape_javascript (render  :partial => 'issues/issue' )  %>");

<%end%>