config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    root    'profiles#show_my_profile'

            #UserController
    get 'user_signup'    => 'users#new'
    
    post 'user_login'    => 'users#login'

    delete 'user_logout' => 'users#destroy'

    get 'user_logout' => 'users#destroy'




    get "show_my_profile" => "profiles#show_my_profile"


    get 'users/:id/:tab' => 'profiles#show_tabs'
    

    #Issues
    get 'add_issue_view' => 'issues#add_issue_view'
    post 'add_issue' => 'issues#add_issue'
    post 'add_issue_comment' => 'issues#add_issue_comment'

    get 'issues/:id/' => 'issues#open_issue'

    post 'user_close_ticket' => 'issues#user_close_ticket'
    post 'user_reopen_ticket' => 'issues#user_reopen_ticket'
    post 'agent_close_ticket' => 'issues#agent_close_ticket'
    post 'agent_assign_ticket' => 'issues#agent_assign_ticket'



    get 'admin/:name' => 'profiles#admin_view'
    post 'user_suspend' => 'profiles#user_suspend'

    get 'generate_report' => 'profiles#generate_report'

    




    

    resources :users  


end

app/models/user.rb
require "core/user_core"
require "core/agent_core"
class User < ApplicationRecord
	before_save{self.email=email.downcase}
	validates :username, presence:  true, length:{maximum:255},uniqueness: {case_sensitive:false}
	validates :email, presence: true, length:{maximum:255}, uniqueness: {case_sensitive:false}
	has_secure_password
	validates :password, length:{minimum:8}

    mount_uploader :profilepic, LogoUploaderUploader



    def anonymous_profilepic
        return "user_no_image5.jpg"
    end

    def get_profile_pic
		if profilepic && profilepic.length>0 then 
			return profilepic
		end
		if self.user?
			return "user_no_image5.jpg" 
		else
			return "user_no_image6.png" 
		end

	end
    def get_profile_pic_url
		if profilepic && profilepic.length>0 then 
			return profilepic.url
		end
        return nil
	end


	#This accessor will have a unique string and the database will have a digest version of this string for 
	#the user who is logged in currently
	attr_accessor :remember_token


    	#This can execute any sql and give result as Mysql2::Result. NEVER CALL THIS FUNCTION
	def self.executesql(sql)
		
		records_array = ActiveRecord::Base.connection.execute(sql)
	end
	# Returns the hash digest of the given string.
	def digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random string token.
	def new_token
		SecureRandom.urlsafe_base64
	end

	#Saves the remember token in db
	def remember
		#This creates and assignes a new string token into the accessor
		self.remember_token = new_token
		#We can call update_attribute directly becoz we are alredy in the Model object
		#update_attribute can change db itemw for users without passing in a password
		update_attribute(:remember_digest, digest(remember_token))
	end

	def get_remembertoken
		return self.remember_token
	end

	# Returns true if the given token matches the digest.
	def authenticated?(remember_token)
		#if logged in from multiple browsers, and logged out from 1, this cud be null
		return false if remember_digest.nil?
		#hashes the token and compares it with digest
		BCrypt::Password.new(remember_digest).is_password?(remember_token)# you can use == also in place of is_password
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end

	def user?
		return true if user_type==0
	end	
	def agent?
		return true if user_type==1
	end	
	def admin?
		return true if user_type==2
	end

	def get_user_object
		if user?
			obj=UserCore.new self
		elsif agent?
			obj=AgentCore.new self
		end
	end

	def get_updates page, page_num
		obj=get_user_object 
		obj.get_data page, page_num
		
	end

	def toggle_suspension
		newval=(self.active==0 ) ? 1 : 0
		self.update_attribute('active', newval)
	end

	def suspended?
		return true unless self.active==1
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   include UsersHelper
    include ProfilesHelper

PAGINATION_PERPAGE=10
    
  #Shows the page to login and signup
  def new
    #When login fails, it comes here
      @user=User.new
  end
    
   

#Shows the profile for a user after logging in 
  def show
  	#if a request comes in to show a users profile page it comes here. From the id get the user
  	@user=User.find_by(id: params[:id])
  	#Show the page only if this user is the currently logged in user
  	if @user.nil? || @user!=current_user then
  		#if the user dosent exist or if he is not currently logged in we redirect him  to homepage
        @user=User.new
  		redirect_to home_path


  	end
    if current_user
        #summarise_updates_for_public_timeline 
    end
    
            
    respond_to do |format|
        format.html do 
            render "users/show"
        end
    end
  end
      


    


      #serves the POST op for  sign up andd HOME PAGE after login
  def create
  	#Create a model object using the input from the form. We cant use the params directly becoz of safety reasons.
  	#So we call a function which explicitely permits the operation
  	@user=User.new(user_params)
      
  	#if the signup is succeeded then we redirect him to homepage
  	if @user.save then 
  		#Commenting below login code becoz we dont want to login user just after signup. We will send a mail and user will have to activate his acciunt
  		log_in @user
  		
                
        #Todo: do not log him in yet. make him activate his account first
  		redirect_to @user
  	else
	  	#If the save failed for whatever reason(mostly becoz of validations,) then redirect him to new template(not new action).
		#here becoz the values are present in adminuser, it will be visible in the form
  		render 'new'
  	end

  end

#serves the POST op for  login
#called when login is done by admin or recruiter
  def login
    	#find the user by username. here session is the hash inside params coz that is what we specified in the form_for of login
  	user=User.find_by(username: params[:session][:username])
  	#if user is not admin check him in the user model
  	if user.nil?
  		user=User.find_by(username: params[:session][:username])
  	end
  	#if the user is present as well as password matches. authenticate api is provided by has_secure_password
  	if(user && user.authenticate(params[:session][:password]))
  		#call the log_in method inside admin_users_helper
  		log_in user
  		#this function will save id and token in browser and hashed token in db
  		remember user 
  		#redirect to profile page. Note again that modelobjectname serves the purpose of routing to appropriate page
      if user.admin?
        redirect_to '/admin/user_list'
      else
    		redirect_to show_my_profile_path
      end
  	else
  		#in case of unsuceesful login 
  		if !user 
  			#if there was no user then username was also wrong
  			flash[:danger]="Invalid username or password"
  		else
  			#user was present in which case only password mismatched
  			flash[:danger]="Invalid password"
  		end
      #I dont know right now which is the best page to redirect hi to. but taking hi to landing page now
      #redirect_to user_signup_path
      redirect_to root_path
  	end
  end

  #called when admins and recruiters logout
  def destroy
  	#call logout method in admin_helper but only if we r loggedin
  	log_out if logged_in?
  	#redirect him to homepage
  	redirect_to root_path
  end


  private 	
  		#This function simply guves a secure way to access params
  		def user_params#called as strong parameters
            params.require(:user).permit(:username,:email,:password,:password_confirmation)
  		end

end

app/helpers/users_helper.rb
module UsersHelper
	 #Logs a adminuser in, we only set cookie. currentuser var is set only when its function  is called
	def log_in (user)
		#Session is a rails method which saves something called as userid in a cookie
		session[:user_name]=user.username

	end

	def find_user(param)
	  	#find the user by username. here session is the hash inside params coz that is what we specified in the form_for of login
		user=User.find_by(param)
		return user
	end

	#gets the currently logged in user
    def get_current_user
		#if there is a session object, use it. otherwise look at the cookie
		if (user_name = session[:user_name])#This is not comparing with user_name. it is assigning to it
			#if currentuser has someone it returns him. if it is the first call it will be empty in which case
			#we check the cookie and get the id of the guy who is logged in
			#@current_user ||= AdminUser.find_by(username: user_name)
			@current_user ||= find_user(username: user_name)

		#if there was no session id it means either nothing is saved or browser was closed. check for cookie
		elsif (user_name = cookies.signed[:user_name])	#The signed function will decrypt the id and give
			#find the user in db whose id is stored in cookie
			#user = AdminUser.find_by(username: user_name)	
			user = find_user(username: user_name)	

			 #The authenticated? method is defined in AdminUser model and authenticates this against what is saved in db using remember token
			 #So that way it comes to know if the id belongs to the same guy who was logged in prevoiusly
			if user && user.authenticated?(cookies[:remember_token])
				#log in the user
				log_in user
				#update the variable so that next time it doesnt have to execute this elseif statement
				@current_user = user
			end
		end
	end
    
    def current_user
        return get_current_user
    end
	
	#calls the current_user method and tells if anyone is logged in at all
	def logged_in?
		#if currentuser.nil returns true then logedin is false
		!current_user.nil?
	end

	#Logs a admin user out
	def log_out
		#delete the cookie
		forget(current_user)
		#delete the sessionid
  		session[:user_name]=nil
  		#then currentuser is deleted
		current_user=nil
	end

	# Remembers a user in a persistent session.
	def remember(user)
		#calls the remember method in AdminUser model
		user.remember
		#cookies method helps to do permanent sessions. This is actually a syntactic sugar for a bigger thing. 
		cookies.permanent.signed[:user_name] = user.username
		#save the remembertoken as well. this dosent need to be encrypted
		cookies.permanent[:remember_token] = user.remember_token
	end

	# Forgets a persistent session.
	def forget(user)
		#call the model.forget api to delete the remember_token from user
		user.forget
		#remove cookie from browser
		cookies[:user_name]=nil
		#remove remembertoken from browser
		cookies[:remember_token]=nil
	end


	def numberize number
		return number
	end
	#function which decieds what I can do. ie if i hav access to post artcles, comment discussion etc
	#it checkes action against user badge and other credentials
	def access action
		if current_user
        	return true
        else
        	return false
        end

	end
end

app/views/users/_landing_page.html.erb
<div class="landingpage">
    
    <section class="jumbotron text-xs-center" >
        <div class="container">
                <h1 class="jumbotron-heading">Best support software</h1>
                <p class="lead text-muted">Raise service tickets to solve your issues..</p>
                <div>
                    <a href="#user_login_holder" class="btn btn-info show_signuplink">Join</a>
                    <a href="#user_login_holder" class="btn btn-secondary show_loginlink">Sing In</a>
                </div>




        </div>
    </section>


    <div class="album text-muted">
        <div class="container">

            <div class="row">
                <div class="card">
                    <img src="assets/a1.jpg" alt="">
                    <p class="card-text">Log ticket</p>
                </div>
                <div class="card">
                    <img src="assets/a2.png" alt="">
                    <p class="card-text">Wait to know status</p>
                </div>
                <div class="card">
                    <img src="assets/a3.png" alt="pic3">
                    <p class="card-text">Be happy once done</p>
                </div>
            </div>

        </div>
    </div>

    <div id="login_snippet_holder" class="hide">
                     <%=render  :partial => 'users/login' %>
    </div>
    <div id="signup_snippet_holder" class="hide">
                     <%=render  :partial => 'users/signup' %>
    </div>
    <section class="video-tutorial">
            <!--container start-->
            <div class="container" id="user_login_holder">
                     <%=render  :partial => 'users/login' %>

            </div>
            
    </section>

</div>


    <script type="text/javascript">
        $(document).on("click",".show_loginlink",function(){
            $("#user_login_holder").html($("#login_snippet_holder").html())
                
        });
        $(document).on("click",".show_signuplink",function(){
            $("#user_login_holder").html($("#signup_snippet_holder").html())
                
        });

    
    </script>

app/views/users/_login.html.erb
<div class="login-bg">
    <div class="container">
        <div class="form-wrapper">
        <%= form_for(:session, url: user_login_path,html:{class:"form-signin wow fadeInUp"}) do |f| %>
                <h2 class="form-signin-heading">sign in now</h2>
                <div class="login-wrap">
                    <%=     f.text_field :username,placeholder:"User ID", class:"form-control" ,autofocus:true%>
                    <%=     f.password_field :password,placeholder:"Password", class:"form-control"%>
                    <label class="checkbox">
                        <input type="checkbox" value="remember-me"> Remember me
                        <span class="pull-right">
                            <a data-toggle="modal" href="#myModal"> Forgot Password?</a>

                        </span>
                    </label>
                    <button class="btn btn-lg btn-login btn-block" type="submit">Sign in</button>

                    <p>or you can sign in via social network</p>
                    <div class="login-social-link">
                        <a href="index.html" class="facebook">
                            <i class="fa fa-facebook"></i>
                            Facebook
                        </a>
                        <a href="index.html" class="twitter">
                            <i class="fa fa-twitter"></i>
                            Twitter
                        </a>
                    </div>
                    <div class="registration">
                        Don't have an account yet?
                        <a class="show_signuplink" href="#user_login_holder">
                            Create an account
                        </a>
                    </div>

                </div>
        <% end%>


      </div>
    </div>
</div>

app/views/users/_signup.html.erb
                    <div class="registration-bg">
                        <div class="container">

                            <%= form_for(@user,html:{class:"form-signin wow fadeInUp"}) do |f| %>
                                <h2 class="form-signin-heading">Register now</h2>
                                <div class="login-wrap">
                                    <p>Enter personal details</p>
                                      <%=   f.text_field :username, class:"form-control", placeholder: :username%>
                                    <%=   f.email_field :email, class:"form-control", placeholder: :emailid%>
                                    <%=   f.password_field :password, class:"form-control", placeholder: :password%>
                                    <%=   f.password_field :password_confirmation, class:"form-control", placeholder: "Confirm Password"%>
                                    <label class="checkbox">
                                        <input type="checkbox" value="agree this condition"> I agree to the Terms of Service and Privacy Policy
                                    </label>
                                    <button class="btn btn-lg btn-login btn-block" type="submit">Submit</button>

                                    <div class="registration">
                                        Already Registered ?
                                        <a class="show_loginlink" href="#user_login_holder">
                                            Login
                                        </a>
                                    </div>
                                </div>
                            <% end%>

                        </div>
                     </div>