config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    root    'profiles#show_my_profile'

            #UserController
    get 'user_signup'    => 'users#new'
    
    post 'user_login'    => 'users#login'

    delete 'user_logout' => 'users#destroy'

    get 'user_logout' => 'users#destroy'




    get "show_my_profile" => "profiles#show_my_profile"


    get 'users/:id/:tab' => 'profiles#show_tabs'
    

    #Issues
    get 'add_issue_view' => 'issues#add_issue_view'
    post 'add_issue' => 'issues#add_issue'
    post 'add_issue_comment' => 'issues#add_issue_comment'

    get 'issues/:id/' => 'issues#open_issue'

    post 'user_close_ticket' => 'issues#user_close_ticket'
    post 'user_reopen_ticket' => 'issues#user_reopen_ticket'
    post 'agent_close_ticket' => 'issues#agent_close_ticket'
    post 'agent_assign_ticket' => 'issues#agent_assign_ticket'



    get 'admin/:name' => 'profiles#admin_view'
    post 'user_suspend' => 'profiles#user_suspend'

    get 'generate_report' => 'profiles#generate_report'

    




    

    resources :users  


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	include UsersHelper
    include ProfilesHelper
    
    IMAGES_PERPAGE=20
    
    
	def show_my_profile



        if current_user
            if current_user.admin?
                redirect_to '/admin/users'
                return
            end

        	page_num= params[:page] ? params[:page] : 1
            @updates=current_user.get_updates "new", page_num
        else
            @user=User.new
        end
        
        

        respond_to do |format|
            format.html do 
                render "users/show"
            end
        end
        
    end





    def show_tabs
        id=params[:id]
        tab=params[:tab]
            @success=false

        @person=User.find_by(id:id)

        if current_user && current_user.id==@person.id
            page_num= params[:page] ? params[:page] : 1
           
            @updates=current_user.get_updates tab, page_num

            @success=true

        end

		respond_to do |format|
            format.html do 
                render "users/show"

            end
		end
    end

    def admin_view
        if current_user && current_user.admin?
            name= params[:name] 
            if name=="users"
                @type="users"
                @users=User.where(user_type: 0).limit(20);
            else
                @type="agents"
                @users=User.where(user_type: 1).limit(20);
            end
        end
        respond_to do |format|
            format.html do 
                render "users/show"
            end
        end
        
    end

 
    def user_suspend
        id= params[:id] 
        begin
            throw 'unauthorized' unless current_user.admin?
            @user=User.find_by(id:id)
            @user.toggle_suspension
            if @user.suspended?
                @text='Unblock'
            else
                @text='Block'
            end


        rescue Exception=>ex
            debugger
        end
        @type="user_suspend"
        respond_to do |format|
            format.js {render :file => "profiles/ajaxresponse/show_my_profile.js.erb" }
        end

    end

    def generate_report
        #pdf info taken from https://stackoverflow.com/questions/33150683/rails-wicked-pdf-convert-page-as-pdf
        @updates=current_user.get_updates "all", 0
        respond_to do |format|
            format.pdf do
                render pdf: "file_name.pdf"   # Excluding ".pdf" extension.
            end
        end
        
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

	def get_updates
	end
end

app/views/profiles/ajaxresponse/_admin_sidebar.html.erb
<div class="profilesidebar">

<%maxgroups=4%> 
    
    <div class="container-fluid main-container">
            <div class="sidebar">
                <div class="row">
                        <!-- Menu -->
                        <div class="side-menu">
                            <nav class="navbar navbar-default" role="navigation">
                                <!-- Main Menu -->
                                <div class="side-menu-container">
                                    <ul class="nav navbar-nav">
                                        <li class="active"><%= link_to( "Users", "/admin/users" , id:"" ,class:"") %>
                                        </li>

                                        <li class=""><%= link_to( "Agents", "/admin/agents" , id:"" ,class:"") %>
                                        </li>

                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </nav>

                        </div>
                </div>      
        </div>

    </div><!--Container end-->
</div>
<script>
  $(function () {
    $('.navbar-toggle-sidebar').click(function () {
      $('.navbar-nav').toggleClass('slide-in');
      $('.side-body').toggleClass('body-slide-in');
      $('#search').removeClass('in').addClass('collapse').slideUp(200);
    });

    $('#search-trigger').click(function () {
      $('.navbar-nav').removeClass('slide-in');
      $('.side-body').removeClass('body-slide-in');
      $('.search-input').focus();
    });
  });
</script>

app/views/profiles/ajaxresponse/_agent_list.html.erb
<% @users && @users.each do |user|%>
    <div class="col-md-9">
            <div class="detailBox">
                <div class="titleBox">
                  <label><h4><%=user.username%></h4></label>
                </div>
                <div class="commentBox">
                    <div class="post_content_actual">
                        other infoss
                    </div>

                </div>

                <div class="actionBox">

                 







                </div>

            </div>
    </div>
<%end%>

app/views/profiles/ajaxresponse/_issues.html.erb
<%if @updates.nil? or @updates.count==0%>
<p>No Issues to show</p>
<%else%>
	<div class=" " id="issue_area">
	</div>

	<%= javascript_tag "updates = #{@updates.to_json.html_safe};" %>

	<script type="text/jsx">
	console.log(updates);
	//alert(updates);

		var Issues=React.createClass({
			createIssues: function (updates) {
			    return updates.map(this.createIssue);
			  },
			  createIssue: function (update) {
			    return (
	            	<div class="col-md-9">
	                    <div class="detailBox">
	                        <div class="titleBox">
	                        <a href={"/issues/"+update.id}>{update.heading}</a>
	                          <label></label>
	                        </div>
	                        <div class="commentBox">
	                            <div class="post_content_actual">
	                            </div>

	                        </div>
	                        <div class="actionBox">

	                        </div>

	                    </div>
	                </div> );
			  },

			render: function(){
				return (
					      <div className="container">
					        <div className="row">
					          <div className="col-sm-12 ">

					            {this.createIssues(updates)}

					          </div>
					        </div>
					      </div>
					    );
			}
		});

		React.render(<div><Issues /></div>, document.getElementById('issue_area') )

	</script>
<%end%>

app/views/profiles/ajaxresponse/_show_admin_profile.html.erb
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-xs-3" >
                <div class="home_profile_imagearea">
                      <ul class="list-group">
                        <li class="list-group-item no-padding"><%= image_tag current_user.get_profile_pic ,   class:" img-responsive"%></li>
                        <li id="profile-about" class="list-group-item text-center">
                            <h3><%= current_user.username%></h3>
                        </li>
                      </ul>
                </div>
                <%= render partial: "profiles/ajaxresponse/admin_sidebar" %>


                

            </div>



            <div class="col-sm-9 " id="post_area">
                <h2>Issues</h2>

                <div class="post_area2">
                    
                    <%if @type=="users"%>
                        <%= render partial: "profiles/ajaxresponse/user_list" %>
                    <%else%>
                        <%= render partial: "profiles/ajaxresponse/agent_list" %>

                    <%end%>


               

                </div>  
            </div>

        </div>
    </div>

app/views/profiles/ajaxresponse/_show_agent_profile.html.erb
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-xs-3" >
                <div class="home_profile_imagearea">
                      <ul class="list-group">
                        <li class="list-group-item no-padding"><%= image_tag current_user.get_profile_pic ,   class:" img-responsive"%></li>
                        <li id="profile-about" class="list-group-item text-center">
                            <h3><%= current_user.username%></h3>
                        </li>
                      </ul>
                </div>
                <%= render partial: "profiles/ajaxresponse/sidebar" %>


                

            </div>



            <div class="col-sm-9 " id="post_area">
                <h2>Issues</h2>

                <div class="post_area2">
                    
                    <%if @type=="open_issue"%>
                        <%= render partial: "issues/issue" %>
                    <%else%>
                      <div class="col-md-3 pull-right">     
                                <%= link_to "Generate Report" , generate_report_path(format: :pdf), method:  :get,  id:"",class:"btn btn-success"%>
                            </div>
                        <%= render partial: "profiles/ajaxresponse/issues" %>

                    <%end%>


               

                </div>  
            </div>

        </div>
    </div>

app/views/profiles/ajaxresponse/_show_profile.html.erb
<% unless current_user  %>
    <%= render partial: "users/landing_page" %>

<%else%>

    <% if current_user.user?  %>
        <%= render partial: "profiles/ajaxresponse/show_user_profile" %>

    <%elsif current_user.agent?%>
        <%= render partial: "profiles/ajaxresponse/show_agent_profile" %>
    <%elsif current_user.admin?%>
        <%= render partial: "profiles/ajaxresponse/show_admin_profile" %>


    <%end%>


<%end%>

app/views/profiles/ajaxresponse/_show_user_profile.html.erb
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-xs-3" >
                <div class="home_profile_imagearea">
                      <ul class="list-group">
                        <li class="list-group-item no-padding"><%= image_tag current_user.get_profile_pic ,   class:" img-responsive"%></li>
                        <li id="profile-about" class="list-group-item text-center">
                            <h3><%= current_user.username%></h3>
                        </li>
                      </ul>
                </div>


                    <%= render partial: "profiles/ajaxresponse/sidebar" %>



                

            </div>



            <div class="col-sm-9 " id="post_area">
                <h2>Issues</h2>
            

                <div class="post_area2">
                    
                    <%if @type=="open_issue"%>
                        <%= render partial: "issues/issue" %>
                    <%else%>
                        <%if current_user.suspended?%>
                            <p>Your account is blocked. You cant create issues</p>
                        <%else%>
                            <div class="col-md-3 pull-right">     
                                <%= link_to "Create Issue" , add_issue_view_path, method:  :get, remote:true , id:"",class:"btn btn-success"%>
                            </div>
                        <%end%>

                        <%= render partial: "profiles/ajaxresponse/issues" %>

                    <%end%>


               

                </div>  
            </div>

        </div>
    </div>

app/views/profiles/ajaxresponse/_sidebar.html.erb
<div class="profilesidebar">

<%maxgroups=4%>	
    
    <div class="container-fluid main-container">
            <div class="sidebar">
                <div class="row">
                        <!-- Menu -->
                        <div class="side-menu">
                            <nav class="navbar navbar-default" role="navigation">
                                <!-- Main Menu -->
                                <div class="side-menu-container">
                                    <ul class="nav navbar-nav">
                                        <li class="active"><%= link_to( "New Issues", "/users/#{current_user.id}/new" , id:"" ,class:"") %>
                                        </li>

                                        <li class=""><%= link_to( "Open Issues", "/users/#{current_user.id}/open" , id:"" ,class:"") %>
                                        </li>

                                        <li class=""><%= link_to( "Closed Issues", "/users/#{current_user.id}/closed" , id:"" ,class:"") %>
                                        </li>

                                        <li class=""><%= link_to( "All Issues", "/users/#{current_user.id}/all" , id:"" ,class:"") %>
                                        </li>

                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </nav>

                        </div>
                </div>  		
        </div>

    </div><!--Container end-->
</div>
<script>
  $(function () {
  	$('.navbar-toggle-sidebar').click(function () {
  		$('.navbar-nav').toggleClass('slide-in');
  		$('.side-body').toggleClass('body-slide-in');
  		$('#search').removeClass('in').addClass('collapse').slideUp(200);
  	});

  	$('#search-trigger').click(function () {
  		$('.navbar-nav').removeClass('slide-in');
  		$('.side-body').removeClass('body-slide-in');
  		$('.search-input').focus();
  	});
  });
</script>

app/views/profiles/ajaxresponse/_user_list.html.erb
<% @users && @users.each do |user|%>
    <div class="col-md-9">
            <div class="detailBox">
                <div class="titleBox">
                  <label><h4><%=user.username%></h4></label>
                </div>
                <div class="commentBox">
                <%text='Block'%>
                <%if user.suspended?%>
                    <%text='UnBlock'%>
                <%end%>
                  <button type="button" class="btn btn-success user_suspend" id='user_suspend<%=user.id%>'  userid="<%=user.id%>" ><%=text%></button>


                </div>

                <div class="actionBox">

                 







                </div>

            </div>
    </div>
<%end%>

app/views/profiles/ajaxresponse/show_my_profile.js.erb
<%if @type=="user_suspend"%>
    $('#user_suspend<%=@user.id%>').html("<%=  @text %>");

<%end%>