config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    root    'profiles#show_my_profile'

            #UserController
    get 'user_signup'    => 'users#new'
    
    post 'user_login'    => 'users#login'

    delete 'user_logout' => 'users#destroy'

    get 'user_logout' => 'users#destroy'




    get "show_my_profile" => "profiles#show_my_profile"


    get 'users/:id/:tab' => 'profiles#show_tabs'
    

    #Issues
    get 'add_issue_view' => 'issues#add_issue_view'
    post 'add_issue' => 'issues#add_issue'
    post 'add_issue_comment' => 'issues#add_issue_comment'

    get 'issues/:id/' => 'issues#open_issue'

    post 'user_close_ticket' => 'issues#user_close_ticket'
    post 'user_reopen_ticket' => 'issues#user_reopen_ticket'
    post 'agent_close_ticket' => 'issues#agent_close_ticket'
    post 'agent_assign_ticket' => 'issues#agent_assign_ticket'



    get 'admin/:name' => 'profiles#admin_view'
    post 'user_suspend' => 'profiles#user_suspend'

    get 'generate_report' => 'profiles#generate_report'

    




    

    resources :users  


end

app/views/layouts/_common_snippets.erb
<div class=" hide" id="waitgif">
    <div class="container">
        <%= image_tag "wait.gif",  class:"icon"%>

    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	@Copyright Somename
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
            <li><%= link_to "FAQ", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
                <%= link_to "ServiceDesk", root_path, id: "logo" %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          </div>
      <div class="collapse navbar-collapse" id="collapse">
        <nav>
          <ul class="nav navbar-nav navbar-right">
                      
                        <li class="active"><%=link_to "Home", '#my_profile_tabcontent' ,"data-toggle"=>"tab",id:"my_profile_tabpane" %></li>

      
                        
                <% if logged_in? %>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Edit Profile", '#' %></li>
                          <li><%= link_to "Settings", '#' %></li>
                          <li><%= link_to "Help", '#' %></li>
                          <li class="divider"></li>
                          <li class="divider"></li>
                          <li><%= link_to "Log out", user_logout_path, method: "delete" %></li>
                        </ul>
                    </li> 
                <%else %>
                     <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Help", '#' %></li>
                            <li class="divider"></li>
                            <li class=""><%=link_to "Players", '#club_tabcontent' ,"data-toggle"=>"tab",id:"club_tabpane" %></li>

                        </ul>
                      </li> 
              <%end%>
          </ul>
        </nav>
      </div>
    </div>
  </header>


<!--  THIS IS CONTENT FOR THE TABS -->
<div class="bs-docs-example">
    <div id="myTabContent" class="tab-content">

      <div class="tab-pane fade in active" id="my_profile_tabcontent">
        <% if logged_in? %>
            <%= render partial: "profiles/ajaxresponse/show_profile" %>
        <%else  %>
            <%@user=User.new%>
          <%= render partial: "users/landing_page" %>
        <%end%>
      </div>  

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Servicedesk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://fb.me/react-0.14.3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0-alpha1/JSXTransformer.js"></script>
    
  </head>

<body>

<%= render 'layouts/header'%>

		<%= yield %>
    <%= render 'layouts/common_snippets' %>

		<%= render 'layouts/footer' %>
</body>
</html>